export const productImages = [{
        id:1,
        productImages:"productImage"
},{
        id:2,
        productImages:"productImage"
},{
        id:3,
        productImages:"productImage"
},{
        id:4,
        productImages:"productImage"
},{
        id:5,
        productImages:"productImage"
},{
        id:6,
        productImages:"productImage"
},{
        id:7,
        productImages:"productImage"
},{
        id:8,
        productImages:"productImage"
}]